### ISSUE TITLE
deprecated Textile method warning with txp 4.7.2

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_featured#1]
Just a heads up: I'm getting `Parser::textileThis() is deprecated. Use Parser::parse() instead.` warnings with the upcoming txp 4.7.2. It points to line 2033 on my site but I suspect it's lines [710-711](https://github.com/Bloke/smd_featured/blob/21920087629313ee8553784b2849269ea37ab152/smd_featured.php#L708-L712) of the plugin.

**Comment by Bloke** [comment]
Yes, thanks for the heads-up. I got that warning in another plugin of mine the other day too. Not fixed it yet but I will do.
